### PR TITLE
Differentiate between two errors

### PR DESCRIPTION
**Pull request by irdkwmnsb**
It's impossible to distinguish the two errors when 'audience' doesn't match.
The first error is programmer's fault – supplying an incorrect audience value.
The second is an expected error – when the audience doesn't match the required value.
The error messages shouldn't be the same.

### CODE REVIEW

**Comment by irdkwmnsb** [comment]
Or does the absence of audience from the JWT token should match the absence of audience in the validate call?
Is it possible to not check the audience?

**Review by auvipy — APPROVED** [review]

**Review by jpadilla — APPROVED** [review]
- Needs updating changelog
- Would changing this be considered a breaking change?

**Comment by irdkwmnsb** [comment]
> * Needs updating changelog
Done.
> * Would changing this be considered a breaking change?
No, since 
1) The error message should not be relied upon error handling
2) If so, this error message already might happen in two different cases, which are indistinguishable, so no logic really aplies there.

**Comment by auvipy** [comment]
yeah agree

**Pull request merged**
