### PR TITLE
Fix type annotation

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Not sure what happened here. It says it accepts Dict or bytes, then the code immediately checks if it is Mapping on the first line...

### CODE REVIEW

**Comment by jdufresne** [comment]
With this change, I receive the following error when running `mypy`:

```
$ tox -e typing
jwt/api_jwt.py:36: error: Argument 1 of "encode" is incompatible with supertype "PyJWS"; supertype defines the argument type as "Union[Dict[Any, Any], bytes]"
jwt/api_jwt.py:36: note: This violates the Liskov substitution principle
jwt/api_jwt.py:36: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
jwt/api_jwt.py:55: error: Unsupported target for indexed assignment ("Mapping[str, Any]")
```

**Comment by Dreamsorcerer** [comment]
Yes, it seems there are numerous issues.

The root cause appears to be a decision to inherit from the base class in an incompatible manner.

Then to try and get Mypy to be quiet, it looks like a bunch of incorrect annotations have been added, in order to lie to mypy and trick it into passing successfully.

It also tries to assign into a `Mapping` type, which could also produce an error, it should be `MutableMapping`.

I've updated the PR to reflect the correct types, but you'll get the error about incorrect inheritance still. I don't know anything about this codebase (I just spotted it while typing another library which depends on this one), so I'll leave it to you to decide how to resolve that. If you really want to keep the incompatible inheritance, then I guess a `type: ignore` comment would work, and would ensure the type annotations remain correct in the public API.

**Comment by Dreamsorcerer** [comment]
I'd suggest adding annotations to the rest of utils.py as well, in order to see how many other errors might be hiding.

**Comment by jdufresne** [comment]
> I'd suggest adding annotations to the rest of utils.py as well, in order to see how many other errors might be hiding.

I agree this would be helpful. Would you like to submit a PR?

**Comment by jdufresne** [comment]
This issue has been reported before, see #396 and #394.

I think we'll need to split the classes apart to some degree so the `.encode()` method can have two different interfaces.

**Comment by Dreamsorcerer** [comment]
Sorry, this was very much meant to be a 30 second contribution. I am trying to work on several other projects right now.

The changes here fix the public API, resolving atleast #394. You can split the classes, or just rename one of the methods (e.g. `encode_token()`), though such a change would need a major version change due to breaking backwards-compatibility.

If that's too complicated right now, then a `type: ignore` on that line can remove the Mypy warning for now (or leave it as a reminder, as you don't have Mypy on your CI checks).

**Comment by jdufresne** [comment]
> It also tries to assign into a Mapping type, which could also produce an error, it should be MutableMapping.

I think the input value shouldn't be mutated, IMO, that is a bit surprising. See #557 to fix this. Mind taking a look?

**Comment by Dreamsorcerer** [comment]
Seems reasonable. Reverted the MutableMapping change.

**Comment by jdufresne** [comment]
I have built off this work in #559 which takes the next step of splitting the classes. Now all type checks pass. Can you please take a look?

**Comment by jdufresne** [comment]
> I'd suggest adding annotations to the rest of utils.py as well, in order to see how many other errors might be hiding.

:+1: I opened PR #564 for this. Would you like to take a look?

**Pull request closed without merging**
