### PR TITLE
Add `as_dict` option to `Algorithm.to_jwk`

### LINKED ISSUE #880: Support returning `Algorithm.to_jwk(key)` as dict
Currently, the when generating a JWK, the only way to get a `dict` from PyJWT is to:

```python
jwk_str = algo.to_jwk(key)
jwk = json.loads(jwk_str)
```

This is very unfortunate when you want to add more fields into the JWK:

```python
modified_jwk = {
    **json.loads(jwk_str),
    "kid": "keyid",
}
```

There should be a way in the API to get the underlying `dict` from the `Algorithm.to_jwk(key)` functions.
My proposal is to add another variant `Algorithm.to_jwk_dict(key)` to not break API compatibility.

I'm planning to send PR implementing this, but I figured I should raise an issue first to see if there's any better way of doing this...

### PR DESCRIPTION
**Pull request by fluxth**
Fixes #880

This patch adds an optional `as_dict=False` keyword argument to `Algorithm.to_jwk()` functions.

Library API is still backwards compatible with this change: 
```
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import jwt
In [2]: algo = jwt.get_algorithm_by_name('HS256')
In [3]: jwk_json = algo.to_jwk('test')

In [4]: type(jwk_json), jwk_json
Out[4]: (str, '{"k": "dGVzdA", "kty": "oct"}')

In [5]: jwk_dict = algo.to_jwk('test', as_dict=True)

In [6]: type(jwk_dict), jwk_dict
Out[6]: (dict, {'k': 'dGVzdA', 'kty': 'oct'})
```

### CODE REVIEW

**Comment by fluxth** [comment]
I think this is ready for review now, the only CI that is failing is codecov for typehint `@overload`s, mypy already checks for that.

**Comment by Viicos** [comment]
@fluxth Regarding failing CI, you can add more to `exclude_lines`:
https://github.com/jpadilla/pyjwt/blob/97711b1a4fc322796092faa6bb18f8097b8eed62/pyproject.toml#L13-L15

**Comment by fluxth** [comment]
CI test flaked, requesting re-run.

**Review by jpadilla — APPROVED** [review]
Looks good to me, thanks! Can you update the changelog?

**Comment by fluxth** [comment]
Thanks for merging! 🚀
Sorry I wasn't able to update the changelog before release, it was nighttime in Japan.

**Pull request merged**
