### PR TITLE
Add a type declaration for PyJWK.key

### PR DESCRIPTION
**Pull request by coderanger**

### CODE REVIEW

**Comment by coderanger** [comment]
In theory this can probably be deduced but the generic-y indirection confused Pyright so just hardwiring it for simplicity and reference.

**Comment by coderanger** [comment]
Any interest in this?

**Review by auvipy — COMMENTED** [review]
what is the value of it?

**Comment by coderanger** [comment]
Anyone using a type checker will not need to cast/mark this and a tiny QoL boost for anyone using an IDE that uses type data for autocomplete.

**Pull request closed without merging**
