### PR TITLE
Update FAQ to clarify Python2/3 differences

### PR DESCRIPTION
**Pull request by dbinetti**
In response to #319

### CODE REVIEW

**Comment by dbinetti** [comment]
sure, although most lines will be the same... not very DRY :-).

**Comment by jpadilla** [comment]
@dbinetti as it is I feel like somebody on Python 3 would try copy pasting most of the code from the snippet, it'll fail, then they might go back and see the note on Python 3.

**Comment by dbinetti** [comment]
I've actually never edited a PR before; is that all I need do?

**Comment by jpadilla** [comment]
@dbinetti yep, that's it. Thanks!

**Pull request merged**
