### PR TITLE
Implementation of ECAlgorithm.from_jwk

### PR DESCRIPTION
**Pull request by evertlammerts**
Support for JWKs containing ECDSA keys

### CODE REVIEW

**Comment by GuillaumeSmaha** [comment]
:cake: 
Any news to merge that ?
@jpadilla are you interested to implement it ?

**Comment by ccakes** [comment]
+1 @jpadilla 

This would be great to have

**Comment by jpadilla** [comment]
Sorry for the delay. Merged this into the work for v2 https://github.com/jpadilla/pyjwt/pull/470

**Comment by jpadilla** [comment]
Closing in favor of #500

**Pull request closed without merging**
