### PR TITLE
README: Add example outputs as comments

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by mark-adams** [comment]
Good point. I'd still like to see us use the doc-string convention though. I think it looks a little better

**Comment by jpadilla** [comment]
@mark-adams you meant `>>>` instead of `>`?

```python
>>> import jwt
>>> jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')
'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb21lIjoicGF5bG9hZCJ9.4twFt5NiznN84AWoo1d7KO1T_yoc0Z6XOpOVswacPZg'
```

I dig that better.

**Comment by mark-adams** [comment]
Oh yea! That's what I meant.

Let's do that instead.

**Comment by mark-adams** [comment]
Merging this and then I'll change the docstrings

**Pull request merged**
