### PR TITLE
Changed to use Pytest as the test runner #111

### LINKED ISSUE #111: Use pytest

### PR DESCRIPTION
**Pull request by mark-adams**
Resolves #111 
* Installed Pytest
* Converted all unittest-related assertions to normal `assert` statements
* Removed all references to unittest from the project

### CODE REVIEW

**Comment by jpadilla** [comment]
Great work with this! I'll look into [creating a pytest standalone script](https://pytest.org/latest/goodpractises.html#create-a-pytest-standalone-script) after this is in. It's what we use in [Django REST framework](https://github.com/tomchristie/django-rest-framework/blob/master/runtests.py).

**Comment by mark-adams** [comment]
Any reason why we need the standalone Pytest script if `setup.py test` works? What benefit do we get?

**Comment by jpadilla** [comment]
Not much benefit as is, other than considered "good practice", but I've grown fond of the one we use and having it run the tests as well as `flake8`.

**Comment by mark-adams** [comment]
@jpadilla This is fixed-up and should be good to go now.

**Pull request merged**
