### PR TITLE
Specify ca file from certifi

### LINKED ISSUE #892: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate
Summary.

It throws this error <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate.

What you expected.

`urllib.request.urlopen` should succeed.

What happened instead.
it unable to fetch the `JWKSet`

## Reproduction Steps

```python
self.signing_key = self.jwks_client.get_signing_key_from_jwt(self.token)
```

## System Information

    $ python -m jwt.help

```
{
  "cryptography": {
    "version": "41.0.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.2"
  },
  "platform": {
    "release": "21.6.0",
    "system": "Darwin"
  },
  "pyjwt": {
    "version": "2.7.0"
  }
}
```

This command is only available on PyJWT v1.6.3 and greater. Otherwise,
please provide some basic information about your system.

### PR DESCRIPTION
**Pull request by michaelhenry**
close #892

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please update unit tests as well

**Comment by jpadilla** [comment]
I'm not sure I see the value of including an additional dependency here. I'd rather see https://github.com/jpadilla/pyjwt/pull/891 get in

**Comment by michaelhenry** [comment]
@jpadilla true, that one is more dynamic. I can close this pr and hopefully to merge it soon. Thanks

**Comment by michaelhenry** [comment]
Closing this pr with respect to #891

**Pull request closed without merging**
