### PR TITLE
Fix for headers disorder issue

### PR DESCRIPTION
**Pull request by kadabusha**
Related issue #715

### CODE REVIEW

**Comment by auvipy** [comment]
lets see if build passes

**Review by auvipy — CHANGES_REQUESTED** [review]
can you please check the CI failures?

**Comment by kadabusha** [comment]
@auvipy would you please give me a hint on these failures?
CI issue is on tox with building some docs with python3.7 and python 3.8 - is there some way to troubleshoot it further?
I suspect some spacing issue that however is not related to my change, perhaps there is a whitespace in expected or something.
Before filing the PR I checked the change with python 3.6 and some old cryptography and pyjwt, and with python 3.9 and latest packages - no issues appeared.
```
  Failed example:
      print(encoded_jwt)
  Expected:
      ***
  Got:
      ***
```

**Comment by auvipy** [comment]
seems sphinx issue

**Comment by jpadilla** [comment]
@kadabusha you'll need to update any snippet in docs that is encoding, like https://github.com/jpadilla/pyjwt/blob/master/docs/usage.rst#encoding--decoding-tokens-with-hs256

**Comment by kadabusha** [comment]
> @kadabusha you'll need to update any snippet in docs that is encoding, like https://github.com/jpadilla/pyjwt/blob/master/docs/usage.rst#encoding--decoding-tokens-with-hs256

Hi, @jpadilla 
Thanks for looking into this.
I do not see any difference in encode() output, it's about get_unverified_header() and order of headers there.
Shall that part of doc be adjusted instead? There is only one match in the docs for get_unverified_header() - ./usage.rst

**No patch:**
```
>>> import jwt;
>>> encoded = jwt.encode({"some": "payload"}, "secret", algorithm="HS256", headers = {"kid": "230498151c214b788dd97f22b85410a5"})
>>> print(encoded);
b'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6IjIzMDQ5ODE1MWMyMTRiNzg4ZGQ5N2YyMmI4NTQxMGE1In0.eyJzb21lIjoicGF5bG9hZCJ9.gdQ884yjlnLnIrYjfQaClE6rJC2x8v2OP2s_eXOLhZA'
>>> jwt.decode(encoded, "secret", algorithms="HS256");
{'some': 'payload'}
>>> jwt.get_unverified_header(encoded)
{'typ': 'JWT', 'alg': 'HS256', 'kid': '230498151c214b788dd97f22b85410a5'}
```

**With patch:**
```
>>> import jwt
>>> print(encoded);
b'eyJhbGciOiJIUzI1NiIsImtpZCI6IjIzMDQ5ODE1MWMyMTRiNzg4ZGQ5N2YyMmI4NTQxMGE1IiwidHlwIjoiSldUIn0.eyJzb21lIjoicGF5bG9hZCJ9.0n16c-shKKnw6gervyk1Dge35tvzbzQ_KCV3H3bgoJ0'
>>> jwt.decode(encoded, "secret", algorithms="HS256");
{'some': 'payload'}
>>> jwt.get_unverified_header(encoded)
{'alg': 'HS256', 'kid': '230498151c214b788dd97f22b85410a5', 'typ': 'JWT'}
```

**Review by auvipy — CHANGES_REQUESTED** [review]
please make the CI green

**Comment by kadabusha** [comment]
@auvipy I added a commit with comment, the checks should be triggered manually I assume.
Your last comment on failures:
```
[auvipy](https://github.com/auvipy) commented [on Dec 30, 2021](https://github.com/jpadilla/pyjwt/pull/721#issuecomment-1002990460)
seems sphinx issue
```

**Comment by kadabusha** [comment]
Seems that some hardcoded data is not returning full match:
https://github.com/jpadilla/pyjwt/runs/7389254685?check_suite_focus=true
```
  Failed example:
      print(encoded_jwt)
  Expected:
      ***
  Got:
      ***
```

**Review by jpadilla — CHANGES_REQUESTED** [review]
you just have to update the tokens in code blocks

```
$ python -m doctest README.rst
**********************************************************************
File "README.rst", line 44, in README.rst
Failed example:
    print(encoded)
Expected:
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzb21lIjoicGF5bG9hZCJ9.Joh1R2dYzkRvDkqv3sygm5YyK8Gi4ShZqbhK2gxcs2U
Got:
    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb21lIjoicGF5bG9hZCJ9.4twFt5NiznN84AWoo1d7KO1T_yoc0Z6XOpOVswacPZg
**********************************************************************
1 items had failures:
   1 of   4 in README.rst
***Test Failed*** 1 failures.
(.venv) jpadilla at hypatia in personal/pyjwt on master [!$]
$ python -m doctest docs/index.rst
**********************************************************************
File "docs/index.rst", line 34, in index.rst
Failed example:
    print(encoded_jwt)
Expected:
    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzb21lIjoicGF5bG9hZCJ9.Joh1R2dYzkRvDkqv3sygm5YyK8Gi4ShZqbhK2gxcs2U
Got:
    eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb21lIjoicGF5bG9hZCJ9.4twFt5NiznN84AWoo1d7KO1T_yoc0Z6XOpOVswacPZg
**********************************************************************
1 items had failures:
   1 of   4 in index.rst
***Test Failed*** 1 failures.
```

**Comment by kadabusha** [comment]
Thanks, @jpadilla @auvipy - updated the PR. Perhaps the commits should be squashed - I added 4 commits for the change.
Otherwise please let me know if new PR with a single commit is to be created.

**Review by auvipy — APPROVED** [review]

**Pull request merged**
