### PR TITLE
Added get_unverified_header method

### LINKED ISSUE #155: Allow for the retrieval of unverified header values
@skion commented on #70 that it might be useful to have a way to parse out the unverified header parameters in the library prior to validating the entire JWT so that, for instance, a key could be looked up using the kid (until we get JWK support completed in 2.0)

We probably should create a jwt.utils function called `get_unverified_header()` or something like that.

### PR DESCRIPTION
**Pull request by mark-adams**
Added get_unverified_header method so that unverified headers can be retrieved by the application. Closes #155

### CODE REVIEW

**Comment by mark-adams** [comment]
Good point @skion. I added it to the global API.

**Comment by jpadilla** [comment]
:+1: LGTM. Might be a good idea to always update the changelog for PR's and changes like this.

**Comment by mark-adams** [comment]
Yep, I totally forgot. Just updated

**Comment by jpadilla** [comment]
@mark-adams :+1:  thanks!

**Comment by skion** [comment]
Thanks guys!

**Pull request merged**
