### PR TITLE
Support Python 3.2

### PR DESCRIPTION
**Pull request by efossier**
Fixes https://github.com/jpadilla/pyjwt/issues/206

### CODE REVIEW

**Comment by jpadilla** [comment]
@mark-adams do you remember where we stand on supporting 3.2?

**Comment by mark-adams** [comment]
@jpadilla I believe we stopped supporting 3.2 because it had too many 3.2-specific issues and it seems like many mainstream libraries were starting to drop support as well.

**Comment by efossier** [comment]
@jpadilla @mark-adams Ah ok, didnt realize that was a deliberate decision. Feel free to close.

**Comment by jpadilla** [comment]
@efossier thanks, closing for now.

**Comment by leason** [comment]
For what it's worth I believe I just ran into the issue that caused this PR to be opened.  I'm running Python 3.6.3 and PyJWT 1.5.3.

**Pull request closed without merging**
